owner: briped
repo: sit
sites:
  - name: WS1 Secure Email Gateway
    url: $WS1SEG_URL
  - name: Exchange ActiveSync
    url: $WS1EAS_URL
    expectedStatusCodes:
      - 401
  - name: WS1 Email Notification Service
    url: $WS1ENS_URL
  - name: WS1 Unified Access Gateway Tunnel Service
    check: "tcp-ping"
    url: $WS1TUN_URL
    port: $WS1TUN_PORT
  - name: WS1 Self-Service Portal
    url: $WS1SSP_URL
  - name: WS1 Content Gateway
    url: $WS1CG_URL
  - name: WS1 Device Management
    url: $WS1DM_URL
  - name: WS1 Device Services
    url: $WS1DS_URL
  - name: WS1 Device Services Enrollment
    url: $WS1DSE_URL
  - name: WS1 App Catalog
    url: $WS1AC_URL
  - name: VIA
    url: $VIA_URL
  - name: LDV
    url: $LDV_URL
    expectedStatusCodes:
      - 200
      - 401
      - 403
  - name: OWA
    url: $OWA_URL

i18n:
  locale: da-DK
  #footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  footer: This page is powered by [Upptime](https://upptime.js.org)

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: xmpl.dk
  baseUrl: /sit
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /sit
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
